Traceback (most recent call last):
  File "snippet.py", line 4, in <module>
    from data_util import *
ImportError: No module named data_util
