Traceback (most recent call last):
  File "snippet.py", line 13, in <module>
    url = sys.argv[1]
IndexError: list index out of range
