Traceback (most recent call last):
  File "snippet.py", line 24, in <module>
    with open('/Users/Ficapy/CodeSpace/Dev/xxx/cert/rsa_public_key_2048.pem', 'r') as f:
11111111111111xd
IOError: [Errno 2] No such file or directory: '/Users/Ficapy/CodeSpace/Dev/xxx/cert/rsa_public_key_2048.pem'
