Traceback (most recent call last):
  File "snippet.py", line 11, in <module>
    from tastypie import fields
  File "/usr/local/lib/python2.7/site-packages/tastypie/fields.py", line 9, in <module>
    from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
ImportError: No module named django.core.exceptions
