Traceback (most recent call last):
  File "snippet.py", line 31, in <module>
    print authenticate_signed_token(argv[1])
IndexError: list index out of range
AUTH:secret_api_key:OGQyYTc3MjYxM2U2N2M4MGNlZDA4NTgwNWQyYzQ4NjA1NGY3MWU0Mg==
