{
  "os": [
    "os.access"
  ],
  "subprocess": [
    "subprocess.Popen",
    "subprocess.communicate"
  ],
  "django.core.exceptions": [
    "ImproperlyConfigured"
  ],
  "django.conf": [
    "settings"
  ],
  "Exception": [
    "EncryptionError"
  ]
}