{
  "functools": [
    "wraps"
  ],
  "django.db.models": [
    "ConstraintModel",
    "constraint"
  ],
  "django.core.exceptions": [
    "ValidationError"
  ],
  "auth": [
    "User"
  ]
}